version: "3.7"

services: 
        mysql-service:
                container_name: mysql-service
                image: mysql:8
                networks:
                        - backend
                env_file:
                        - ./dockerfiles/env/mysql-env.env
                environment:
                        MYSQL_PASSWORD_FILE: /run/secrets/mysql-secret
                        MYSQL_RANDOM_ROOT_PASSWORD: "yes" 
                ports:
                        - "3306:3306"
                volumes:
                        - mysql-data:/var/lib/mysql
                secrets:
                        - mysql-secret     
        web-service:
                build: 
                    context: ./dockerfiles/tomcat
                    dockerfile: ./tomcat-Dockerfile.dockerfile
                image: tomcat-docker
                volumes:
                        - ./target/springTest:/usr/local/tomcat/webapps/springTest
                networks:
                       - backend
                ports:
                       - "8080:8080"
                       - "8000:8000"
                depends_on:
                        - mysql-service
                restart: always
                healthcheck:
                        test: ["CMD","crul", "-f", "http://localhost:8080/springTest" ]
                        interval: 30s
                        timeout: 10s
                        retries: 3
                        start_period: 40s
secrets:
       mysql-secret:
                file: ./dockerfiles/env/mysql-secret.txt
networks:
        backend:
                driver:
                        bridge
volumes:
        mysql-data:

        
