version: "3.7"

services: 
        mysql-service:
                container_name: mysql-service
                image: mysql:8
                networks:
                        - backend
                env_file:
                        - ./dockerfiles/env/mysql-env.env
                environment:
                        MYSQL_PASSWORD_FILE: /run/secrets/mysql-secret
                        MYSQL_RANDOM_ROOT_PASSWORD: "yes" 
                ports:
                        - "3306:3306"
                volumes:
                        - mysql-data:/var/lib/mysql
                secrets:
                        - mysql-secret     
        web-service:
                build: 
                    context: ./
                    dockerfile: ./dockerfiles/tomcat/tomcat-Dockerfile
                image: tomcat-docker
                networks:
                       - backend
                ports:
                       - "8080:8080"
                depends_on:
                        - mysql-service
                links:
                        - mysql-service:mysql-docker
secrets:
       mysql-secret:
                file: ./dockerfiles/env/mysql-secret.txt
networks:
        backend:
                driver:
                        overlay
volumes:
        mysql-data:

        
